// Code generated by dingo; DO NOT EDIT
package main

import Cart "github.com/DanielBcnicode/apigo/Cart"

type Container struct {
	AddItemToCartService	*Cart.AddItemToCartService
	CartMemoryRepository	*Cart.CartMemoryRepository
	GetCartHandle		*Cart.GetCartHandle
	GetCartService		*Cart.GetCartService
	ItemMemoryRepository	*Cart.ItemMemoryRepository
	PostItemHandleService	*Cart.PostItemHandleService
}

var DefaultContainer = NewContainer()

func NewContainer() *Container {
	return &Container{}
}
func (container *Container) GetAddItemToCartService() Cart.AddItemToCartService {
	if container.AddItemToCartService == nil {
		service := Cart.AddItemToCartService{}
		service.CartRepository = container.GetCartMemoryRepository()
		service.ItemRepository = container.GetItemMemoryRepository()
		container.AddItemToCartService = &service
	}
	return *container.AddItemToCartService
}
func (container *Container) GetCartMemoryRepository() Cart.CartMemoryRepository {
	if container.CartMemoryRepository == nil {
		service := Cart.CartMemoryRepository{}
		container.CartMemoryRepository = &service
	}
	return *container.CartMemoryRepository
}
func (container *Container) GetGetCartHandle() Cart.GetCartHandle {
	if container.GetCartHandle == nil {
		service := Cart.GetCartHandle{}
		service.Service = container.GetGetCartService()
		container.GetCartHandle = &service
	}
	return *container.GetCartHandle
}
func (container *Container) GetGetCartService() Cart.GetCartService {
	if container.GetCartService == nil {
		service := Cart.GetCartService{}
		service.CartRepository = container.GetCartMemoryRepository()
		container.GetCartService = &service
	}
	return *container.GetCartService
}
func (container *Container) GetItemMemoryRepository() Cart.ItemMemoryRepository {
	if container.ItemMemoryRepository == nil {
		service := Cart.ItemMemoryRepository{}
		container.ItemMemoryRepository = &service
	}
	return *container.ItemMemoryRepository
}
func (container *Container) GetPostItemHandleService() Cart.PostItemHandleService {
	if container.PostItemHandleService == nil {
		service := Cart.PostItemHandleService{}
		service.Service = container.GetAddItemToCartService()
		container.PostItemHandleService = &service
	}
	return *container.PostItemHandleService
}
